import {
  mdiAccountBoxMultipleOutline,
  mdiBookCogOutline,
  mdiBookLockOutline,
  mdiBallotOutline,
  mdiHomeGroup,
  mdiCashMultiple,
  mdiAccountSupervisorCircleOutline,
  mdiHomeOutline,
  mdiTreasureChest,
  mdiGoogleMyBusiness,
  mdiHomeCityOutline,
  mdiFileDocumentMultipleOutline,
} from "@mdi/js";

export default [
  {
    title: "Produk",
    icon: mdiTreasureChest,
    to: "product",
    resource: "Public",
    action: "read",
    accessPage: "viewProduct",
  },
  {
    title: "Produk Tax",
    icon: mdiTreasureChest,
    to: "product-tax",
    resource: "Public",
    action: "read",
    accessPage: "viewProductTax",
  },
  {
    title: "Outlet",
    to: { name: "outlet" },
    icon: mdiHomeCityOutline,
    resource: "Public",
    action: "read",
    accessPage: "viewOutlet",
  },
  {
    title: "Group Chart Of Account",
    icon: mdiFileDocumentMultipleOutline,
    to: "group-coa",
    resource: "Public",
    action: "read",
    accessPage: "viewGroupChartOfAccount",
  },
  {
    title: "Chart of Account",
    icon: mdiFileDocumentMultipleOutline,
    to: "coa",
    resource: "Public",
    action: "read",
    accessPage: "viewChartOfAccount",
  },
  {
    title: "Activity GL",
    to: { name: "activity-gl" },
    icon: mdiFileDocumentMultipleOutline,
    resource: "Public",
    action: "read",
    accessPage: "viewActivityGL",
  },
  {
    title: "Policy Cash/Bank",
    to: { name: "policy-cash-bank" },
    icon: mdiBallotOutline,
    resource: "Public",
    action: "read",
    accessPage: "viewPolicyCashBank",
  },
  {
    title: "Policy Product",
    to: { name: "policy-product" },
    icon: mdiBallotOutline,
    resource: "Public",
    action: "read",
    accessPage: "viewPolicyProduct",
  },
  {
    title: "Policy Payment Channel",
    to: { name: "policy-payment-channel" },
    icon: mdiBallotOutline,
    resource: "Public",
    action: "read",
    accessPage: "viewPolicyPaymentChannel",
  },
];
