import {
  mdiAccountBoxMultipleOutline,
  mdiAccountSupervisorCircleOutline,
  mdiBallotOutline,
  mdiBookLockOutline,
  mdiCashMultiple,
  mdiGoogleMyBusiness,
  mdiHomeGroup,
  mdiTreasureChest,
  mdiWarehouse,
  mdiAnimationOutline,
} from "@mdi/js";

export default [
  {
    subheader: "Setting",
    resource: "Public",
    action: "read",
    accessPage: [
      "viewUser",
      "viewPartner",
      "viewWarehouse",
      "viewUom",
      "viewOu",
      "viewCashbank",
      "viewMerchantIdentity",
      "viewRoleTask",
      "viewPolicy",
    ],
  },
  {
    title: "User",
    to: { name: "user" },
    icon: mdiAccountBoxMultipleOutline,
    resource: "Public",
    action: "read",
    accessPage: "viewUser",
  },
  {
    title: "Partner",
    to: { name: "partner" },
    icon: mdiAccountSupervisorCircleOutline,
    resource: "Public",
    action: "read",
    accessPage: "viewPartner",
  },
  {
    title: "Warehouse",
    to: { name: "warehouse" },
    icon: mdiWarehouse,
    resource: "Public",
    action: "read",
    // accessPage: "viewWarehouse",
    accessPage: "viewPartner",
  },
  {
    title: "Unit of Measurement",
    to: { name: "uom" },
    icon: mdiAnimationOutline,
    resource: "Public",
    action: "read",
    // accessPage: "viewUom",
    accessPage: "viewPartner",
  },
  {
    title: "Type Partner",
    to: { name: "type-partner" },
    icon: mdiAccountSupervisorCircleOutline,
    resource: "Public",
    action: "read",
    accessPage: "viewTypePartner",
  },
  {
    title: "Unit Bisnis",
    to: { name: "unit-bisnis" },
    icon: mdiHomeGroup,
    resource: "Public",
    action: "read",
    accessPage: "viewOu",
  },
  {
    title: "Cash Bank",
    to: { name: "cash-bank" },
    icon: mdiCashMultiple,
    resource: "Public",
    action: "read",
    accessPage: "viewCashbank",
  },
  {
    title: "Merchant Identity",
    icon: mdiGoogleMyBusiness,
    to: "merchant-identity",
    resource: "Public",
    action: "read",
    accessPage: "viewMerchantIdentity",
  },
  {
    title: "Role",
    to: { name: "role" },
    icon: mdiBookLockOutline,
    resource: "Public",
    action: "read",
    accessPage: "viewRole",
  },
  {
    title: "Policy",
    to: { name: "policy" },
    icon: mdiBallotOutline,
    resource: "Public",
    action: "read",
    accessPage: "viewPolicy",
  },
];
